apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper
  namespace: default
spec:
  containers:
    - name: ubuntu-sleeper
      image: ubuntu
      command:
        - "sleep"
        - "4800"
      securityContext: # Container level
        capabilities:
          add: ["SYS_TIME"] # Container will have the SYS_TIME from Root
