apiVersion: v1
kind: Pod
metadata:
  name: myPod
spec:
  containers:
    - name: redis-container
      image: redis
  tolerations:
    - key: "app"
      operator: "Equal"
      value: "blue"
      effect: "NoSchedule"
