# kubectl create secret generic db-secret --from-literal=DB_Host=sql01 --from-literal=DB_User=root --from-literal=DB_Password=password123
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
data:
  DB_Host: sql01
  DB_User: root
  DB_Password: password123
