apiVersion: v1
kind: Pod
metadata:
  name: webapp-color
  namespace: default
  labels:
    name: webapp-color
spec:
  containers:
    - name: webapp-color
      image: kodekloud/webapp-color
      env:
        - name: APP_COLOR #key
          value: green #value
