apiVersion: v1
items:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      creationTimestamp: "2021-11-09T14:24:31Z"
      labels:
        app.kubernetes.io/name: ingress-nginx
        app.kubernetes.io/part-of: ingress-nginx
      managedFields:
        - apiVersion: rbac.authorization.k8s.io/v1
          fieldsType: FieldsV1
          fieldsV1:
            f:metadata:
              f:labels:
                .: {}
                f:app.kubernetes.io/name: {}
                f:app.kubernetes.io/part-of: {}
            f:roleRef:
              f:apiGroup: {}
              f:kind: {}
              f:name: {}
            f:subjects: {}
          manager: python-requests
          operation: Update
          time: "2021-11-09T14:24:31Z"
      name: ingress-role-binding
      namespace: ingress-space
      resourceVersion: "1272"
      uid: 23dd82c5-58eb-4b55-8b73-6e6e054a27cc
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: ingress-role
    subjects:
      - kind: ServiceAccount
        name: ingress-serviceaccount
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
