apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    tier: db-tier
spec:
  containers:
    - name: postgres
      image: postgres
      env: # adding env variable for the pod 
       - name: POSTGRES_PASSWORD
         value: "mysecretpassword"
